### ISSUE TITLE
Null reference exception on home page when no show loaded

### ISSUE THREAD

**Issue by Tim020** [dreamteamprod/DigiScript#238]
```
show.js:428          GET http://localhost:8080/api/v1/show/sessions 400 (Bad Request)
GET_SHOW_SESSION_DATA @ show.js:428
wrappedActionHandler @ vuex.esm.js:798
dispatch @ vuex.esm.js:483
boundDispatch @ vuex.esm.js:377
mappedAction @ vuex.esm.js:1009
created @ App.vue?./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use%5B0%5D!./node_modules/@vue/cli-service/lib/config/vue-loader-v15-resolve-compat/vue-loader.js??vue-loader-options:22
await in created (async)
invokeWithErrorHandling @ vue.runtime.esm.js:2895
callHook$1 @ vue.runtime.esm.js:3868
Vue._init @ vue.runtime.esm.js:5384
VueComponent @ vue.runtime.esm.js:5511
createComponentInstanceForVnode @ vue.runtime.esm.js:4360
init @ vue.runtime.esm.js:4211
createComponent @ vue.runtime.esm.js:6197
createElm @ vue.runtime.esm.js:6159
patch @ vue.runtime.esm.js:6670
Vue._update @ vue.runtime.esm.js:3608
updateComponent @ vue.runtime.esm.js:3709
Watcher.get @ vue.runtime.esm.js:3301
Watcher @ vue.runtime.esm.js:3291
mountComponent @ vue.runtime.esm.js:3730
Vue.$mount @ vue.runtime.esm.js:8257
eval @ main.js:80
./src/main.js @ index.js:162
__webpack_require__ @ index.js:546
(anonymous) @ index.js:823
__webpack_require__.O @ index.js:585
(anonymous) @ index.js:824
(anonymous) @ index.js:826
show.js:434 Unable to get show sessions
GET_SHOW_SESSION_DATA @ show.js:434
await in GET_SHOW_SESSION_DATA (async)
wrappedActionHandler @ vuex.esm.js:798
dispatch @ vuex.esm.js:483
boundDispatch @ vuex.esm.js:377
mappedAction @ vuex.esm.js:1009
created @ App.vue?./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use%5B0%5D!./node_modules/@vue/cli-service/lib/config/vue-loader-v15-resolve-compat/vue-loader.js??vue-loader-options:22
await in created (async)
invokeWithErrorHandling @ vue.runtime.esm.js:2895
callHook$1 @ vue.runtime.esm.js:3868
Vue._init @ vue.runtime.esm.js:5384
VueComponent @ vue.runtime.esm.js:5511
createComponentInstanceForVnode @ vue.runtime.esm.js:4360
init @ vue.runtime.esm.js:4211
createComponent @ vue.runtime.esm.js:6197
createElm @ vue.runtime.esm.js:6159
patch @ vue.runtime.esm.js:6670
Vue._update @ vue.runtime.esm.js:3608
updateComponent @ vue.runtime.esm.js:3709
Watcher.get @ vue.runtime.esm.js:3301
Watcher @ vue.runtime.esm.js:3291
mountComponent @ vue.runtime.esm.js:3730
Vue.$mount @ vue.runtime.esm.js:8257
eval @ main.js:80
./src/main.js @ index.js:162
__webpack_require__ @ index.js:546
(anonymous) @ index.js:823
__webpack_require__.O @ index.js:585
(anonymous) @ index.js:824
(anonymous) @ index.js:826
vue.runtime.esm.js:4420 [Vue warn]: Error in render: "TypeError: Cannot read properties of null (reading 'name')"

found in

---> <HomeView> at src/views/HomeView.vue
       <App> at src/App.vue
         <Root>
warn @ vue.runtime.esm.js:4420
logError @ vue.runtime.esm.js:2923
globalHandleError @ vue.runtime.esm.js:2919
handleError @ vue.runtime.esm.js:2887
Vue._render @ vue.runtime.esm.js:2589
updateComponent @ vue.runtime.esm.js:3709
Watcher.get @ vue.runtime.esm.js:3301
Watcher @ vue.runtime.esm.js:3291
mountComponent @ vue.runtime.esm.js:3730
Vue.$mount @ vue.runtime.esm.js:8257
init @ vue.runtime.esm.js:4212
merged @ vue.runtime.esm.js:4377
createComponent @ vue.runtime.esm.js:6197
createElm @ vue.runtime.esm.js:6159
updateChildren @ vue.runtime.esm.js:6418
patchVnode @ vue.runtime.esm.js:6498
patch @ vue.runtime.esm.js:6644
Vue._update @ vue.runtime.esm.js:3611
updateComponent @ vue.runtime.esm.js:3709
Watcher.get @ vue.runtime.esm.js:3301
Watcher.run @ vue.runtime.esm.js:3372
flushSchedulerQueue @ vue.runtime.esm.js:3955
eval @ vue.runtime.esm.js:3014
flushCallbacks @ vue.runtime.esm.js:2942
Promise.then (async)
timerFunc @ vue.runtime.esm.js:2967
nextTick @ vue.runtime.esm.js:3024
queueWatcher @ vue.runtime.esm.js:4037
Watcher.update @ vue.runtime.esm.js:3363
Dep.notify @ vue.runtime.esm.js:767
reactiveSetter @ vue.runtime.esm.js:977
proxySetter @ vue.runtime.esm.js:5082
created @ App.vue?./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use%5B0%5D!./node_modules/@vue/cli-service/lib/config/vue-loader-v15-resolve-compat/vue-loader.js??vue-loader-options:23
await in created (async)
invokeWithErrorHandling @ vue.runtime.esm.js:2895
callHook$1 @ vue.runtime.esm.js:3868
Vue._init @ vue.runtime.esm.js:5384
VueComponent @ vue.runtime.esm.js:5511
createComponentInstanceForVnode @ vue.runtime.esm.js:4360
init @ vue.runtime.esm.js:4211
createComponent @ vue.runtime.esm.js:6197
createElm @ vue.runtime.esm.js:6159
patch @ vue.runtime.esm.js:6670
Vue._update @ vue.runtime.esm.js:3608
updateComponent @ vue.runtime.esm.js:3709
Watcher.get @ vue.runtime.esm.js:3301
Watcher @ vue.runtime.esm.js:3291
mountComponent @ vue.runtime.esm.js:3730
Vue.$mount @ vue.runtime.esm.js:8257
eval @ main.js:80
./src/main.js @ index.js:162
__webpack_require__ @ index.js:546
(anonymous) @ index.js:823
__webpack_require__.O @ index.js:585
(anonymous) @ index.js:824
(anonymous) @ index.js:826
vue.runtime.esm.js:2927 TypeError: Cannot read properties of null (reading 'name')
    at Proxy.render (HomeView.vue?./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use%5B0%5D!./node_modules/@vue/vue-loader-v15/lib/loaders/templateLoader.js??ruleSet%5B1%5D.rules%5B3%5D!./node_modules/@vue/cli-service/lib/config/vue-loader-v15-resolve-compat/vue-loader.js??vue-loader-options:11:219)
    at Vue._render (vue.runtime.esm.js:2587:22)
    at VueComponent.updateComponent (vue.runtime.esm.js:3709:21)
    at Watcher.get (vue.runtime.esm.js:3301:27)
    at new Watcher (vue.runtime.esm.js:3291:47)
    at mountComponent (vue.runtime.esm.js:3730:3)
    at Vue.$mount (vue.runtime.esm.js:8257:10)
    at init (vue.runtime.esm.js:4212:13)
    at merged (vue.runtime.esm.js:4377:5)
    at createComponent (vue.runtime.esm.js:6197:9)
```

**Comment by Tim020** [comment]
This was fixed by #239
